import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame } from "remotion";
import { Backdrop, accentAt } from "./components/Backdrop";
import { Streak } from "./components/Ui";
import { AddLanguages } from "./scenes/AddLanguages";
import { BackToBase } from "./scenes/BackToBase";
import { Hook } from "./scenes/Hook";
import { Outro } from "./scenes/Outro";
import { SwitchLanguage } from "./scenes/SwitchLanguage";
import { WriteText } from "./scenes/WriteText";
import { BEATS, DURATION } from "./style";

/**
 * Sixty seconds on one feature: a project that ships in more than one
 * language, and the properties panel that writes each one.
 *
 * Five acts, cut on BEATS, over one continuous set of plates captured from the
 * running editor (public/shots, written by scripts/capture-i18n.js). The only
 * things drawn rather than filmed are the camera, the pointer, the spotlights
 * and the copy: every pixel of app in here is a screenshot of the real thing
 * doing the real thing, including the machine translations, the 12/12 counts
 * and the German that gets typed over them.
 */
export const Languages: React.FC = () => {
  const frame = useCurrentFrame();
  const accent = accentAt(frame);

  return (
    <AbsoluteFill style={{ background: "#04060E" }}>
      {/* Generated by scripts/gen-music.js, with its risers and impacts sitting
          on the same BEATS the acts cut on. */}
      <Audio src={staticFile("music.wav")} volume={0.72} />
      <Backdrop />

      <Sequence from={BEATS.hook} durationInFrames={BEATS.add - BEATS.hook}>
        <Hook />
      </Sequence>
      <Sequence from={BEATS.add} durationInFrames={BEATS.read - BEATS.add}>
        <AddLanguages />
      </Sequence>
      <Sequence from={BEATS.read} durationInFrames={BEATS.write - BEATS.read}>
        <SwitchLanguage />
      </Sequence>
      <Sequence from={BEATS.write} durationInFrames={BEATS.keep - BEATS.write}>
        <WriteText />
      </Sequence>
      <Sequence from={BEATS.keep} durationInFrames={BEATS.out - BEATS.keep}>
        <BackToBase />
      </Sequence>
      <Sequence from={BEATS.out} durationInFrames={DURATION - BEATS.out}>
        <Outro />
      </Sequence>

      {/* One whip per act change, on top of everything, in the colour the act
          is turning into. */}
      <Streak at={BEATS.add - 2} accent={accent} />
      <Streak at={BEATS.read - 2} accent={accent} />
      <Streak at={BEATS.write - 2} accent={accent} />
      <Streak at={BEATS.keep - 2} accent={accent} />
      <Streak at={BEATS.out - 2} accent={accent} />
    </AbsoluteFill>
  );
};
